export const GET_CATS_REQUEST = "GET_CATS_REQUEST";
export const GET_CATS_SUCCESS = "GET_CATS_SUCCESS";
export const GET_CATS_ERROR = "GET_CATS_ERROR";

export const GET_MORE_CATS_REQUEST = "GET_MORE_CATS_REQUEST";
export const GET_MORE_CATS_SUCCESS = "GET_MORE_CATS_SUCCESS";
export const GET_MORE_CATS_ERROR = "GET_MORE_CATS_ERROR";
